name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
  
      - name: Decode google-services.json
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
        # Создаем файл строго внутри подпапки android/app/
        run: |
          mkdir -p android/app
          echo "$FIREBASE_SECRET" > ./android/app/google-services.json

      - name: Build Android App
        # working-directory заставляет команду выполняться внутри папки android
        working-directory: ./android
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          # Путь к APK теперь также учитывает папку android
          path: android/app/build/outputs/apk/debug/*.apk
